[package]
name = "paint_tanks"
version = "0.1.0"
edition = "2024"

[profile.dev]
debug = "full"

[dependencies]
avian3d = "0.3.1"
bevy-inspector-egui = "0.32.0"

[dependencies.bevy]
version = "0.16.1"
features = [
    "bevy_pbr",
    "bevy_gltf"
]
